(function() {
  'use strict';

  const all = [
    {
      name: 'C8',
      natural: true,
      note: 'C',
      octave: 8,
      frequency: 4186.01,
    },
    {
      name: 'B7',
      natural: true,
      note: 'B',
      octave: 7,
      frequency: 3951.07,
    },
    {
      name: 'A♯7/B♭7',
      natural: false,
      note: 'B♭',
      octave: 7,
      frequency: 3729.31,
    },
    {
      name: 'A7',
      natural: true,
      note: 'A',
      octave: 7,
      frequency: 3520.00,
    },
    {
      name: 'G♯7/A♭7',
      natural: false,
      note: 'A♭',
      octave: 7,
      frequency: 3322.44,
    },
    {
      name: 'G7',
      natural: true,
      note: 'G',
      octave: 7,
      frequency: 3135.96,
    },
    {
      name: 'F♯7/G♭7',
      natural: false,
      note: 'G♭',
      octave: 7,
      frequency: 2959.96,
    },
    {
      name: 'F7',
      natural: true,
      note: 'F',
      octave: 7,
      frequency: 2793.83,
    },
    {
      name: 'E7',
      natural: true,
      note: 'E',
      octave: 7,
      frequency: 2637.02,
    },
    {
      name: 'D♯7/E♭7',
      natural: false,
      note: 'E♭',
      octave: 7,
      frequency: 2489.02,
    },
    {
      name: 'D7',
      natural: true,
      note: 'D',
      octave: 7,
      frequency: 2349.32,
    },
    {
      name: 'C♯7/D♭7',
      natural: false,
      note: 'D♭',
      octave: 7,
      frequency: 2217.46,
    },
    {
      name: 'C7',
      natural: true,
      note: 'C',
      octave: 7,
      frequency: 2093.00,
    },
    {
      name: 'B6',
      natural: true,
      note: 'B',
      octave: 6,
      frequency: 1975.53,
    },
    {
      name: 'A♯6/B♭6',
      natural: false,
      note: 'B♭',
      octave: 6,
      frequency: 1864.66,
    },
    {
      name: 'A6',
      natural: true,
      note: 'A',
      octave: 6,
      frequency: 1760.00,
    },
    {
      name: 'G♯6/A♭6',
      natural: false,
      note: 'A♭',
      octave: 6,
      frequency: 1661.22,
    },
    {
      name: 'G6',
      natural: true,
      note: 'G',
      octave: 6,
      frequency: 1567.98,
    },
    {
      name: 'F♯6/G♭6',
      natural: false,
      note: 'G♭',
      octave: 6,
      frequency: 1479.98,
    },
    {
      name: 'F6',
      natural: true,
      note: 'F',
      octave: 6,
      frequency: 1396.91,
    },
    {
      name: 'E6',
      natural: true,
      note: 'E',
      octave: 6,
      frequency: 1318.51,
    },
    {
      name: 'D♯6/E♭6',
      natural: false,
      note: 'E♭',
      octave: 6,
      frequency: 1244.51,
    },
    {
      name: 'D6',
      natural: true,
      note: 'D',
      octave: 6,
      frequency: 1174.66,
    },
    {
      name: 'C♯6/D♭6',
      natural: false,
      note: 'D♭',
      octave: 6,
      frequency: 1108.73,
    },
    {
      name: 'C6',
      natural: true,
      note: 'C',
      octave: 6,
      frequency: 1046.50,
    },
    {
      name: 'B5',
      natural: true,
      note: 'B',
      octave: 5,
      frequency: 987.767,
    },
    {
      name: 'A♯5/B♭5',
      natural: false,
      note: 'B♭',
      octave: 5,
      frequency: 932.328,
    },
    {
      name: 'A5',
      natural: true,
      note: 'A',
      octave: 5,
      frequency: 880.000,
    },
    {
      name: 'G♯5/A♭5',
      natural: false,
      note: 'A♭',
      octave: 5,
      frequency: 830.609,
    },
    {
      name: 'G5',
      natural: true,
      note: 'G',
      octave: 5,
      frequency: 783.991,
    },
    {
      name: 'F♯5/G♭5',
      natural: false,
      note: 'G♭',
      octave: 5,
      frequency: 739.989,
    },
    {
      name: 'F5',
      natural: true,
      note: 'F',
      octave: 5,
      frequency: 698.456,
    },
    {
      name: 'E5',
      natural: true,
      note: 'E',
      octave: 5,
      frequency: 659.255,
    },
    {
      name: 'D♯5/E♭5',
      natural: false,
      note: 'E♭',
      octave: 5,
      frequency: 622.254,
    },
    {
      name: 'D5',
      natural: true,
      note: 'D',
      octave: 5,
      frequency: 587.330,
    },
    {
      name: 'C♯5/D♭5',
      natural: false,
      note: 'D♭',
      octave: 5,
      frequency: 554.365,
    },
    {
      name: 'C5',
      natural: true,
      note: 'C',
      octave: 5,
      frequency: 523.251,
    },
    {
      name: 'B4',
      natural: true,
      note: 'B',
      octave: 4,
      frequency: 493.883,
    },
    {
      name: 'A♯4/B♭4',
      natural: false,
      note: 'B♭',
      octave: 4,
      frequency: 466.164,
    },
    {
      name: 'A4',
      natural: true,
      note: 'A',
      octave: 4,
      frequency: 440.000,
    },
    {
      name: 'G♯4/A♭4',
      natural: false,
      note: 'A♭',
      octave: 4,
      frequency: 415.305,
    },
    {
      name: 'G4',
      natural: true,
      note: 'G',
      octave: 4,
      frequency: 391.995,
    },
    {
      name: 'F♯4/G♭4',
      natural: false,
      note: 'G♭',
      octave: 4,
      frequency: 369.994,
    },
    {
      name: 'F4',
      natural: true,
      note: 'F',
      octave: 4,
      frequency: 349.228,
    },
    {
      name: 'E4',
      natural: true,
      note: 'E',
      octave: 4,
      frequency: 329.628,
    },
    {
      name: 'D♯4/E♭4',
      natural: false,
      note: 'E♭',
      octave: 4,
      frequency: 311.127,
    },
    {
      name: 'D4',
      natural: true,
      note: 'D',
      octave: 4,
      frequency: 293.665,
    },
    {
      name: 'C♯4/D♭4',
      natural: false,
      note: 'D♭',
      octave: 4,
      frequency: 277.183,
    },
    {
      name: 'C4',
      natural: true,
      note: 'C',
      octave: 4,
      frequency: 261.626,
    },
    {
      name: 'B3',
      natural: true,
      note: 'B',
      octave: 3,
      frequency: 246.942,
    },
    {
      name: 'A♯3/B♭3',
      natural: false,
      note: 'B♭',
      octave: 3,
      frequency: 233.082,
    },
    {
      name: 'A3',
      natural: true,
      note: 'A',
      octave: 3,
      frequency: 220.000,
    },
    {
      name: 'G♯3/A♭3',
      natural: false,
      note: 'A♭',
      octave: 3,
      frequency: 207.652,
    },
    {
      name: 'G3',
      natural: true,
      note: 'G',
      octave: 3,
      frequency: 195.998,
    },
    {
      name: 'F♯3/G♭3',
      natural: false,
      note: 'G♭',
      octave: 3,
      frequency: 184.997,
    },
    {
      name: 'F3',
      natural: true,
      note: 'F',
      octave: 3,
      frequency: 174.614,
    },
    {
      name: 'E3',
      natural: true,
      note: 'E',
      octave: 3,
      frequency: 164.814,
    },
    {
      name: 'D♯3/E♭3',
      natural: false,
      note: 'E♭',
      octave: 3,
      frequency: 155.563,
    },
    {
      name: 'D3',
      natural: true,
      note: 'D',
      octave: 3,
      frequency: 146.832,
    },
    {
      name: 'C♯3/D♭3',
      natural: false,
      note: 'D♭',
      octave: 3,
      frequency: 138.591,
    },
    {
      name: 'C3',
      natural: true,
      note: 'C',
      octave: 3,
      frequency: 130.813,
    },
    {
      name: 'B2',
      natural: true,
      note: 'B',
      octave: 2,
      frequency: 123.471,
    },
    {
      name: 'A♯2/B♭2',
      natural: false,
      note: 'B♭',
      octave: 2,
      frequency: 116.541,
    },
    {
      name: 'A2',
      natural: true,
      note: 'A',
      octave: 2,
      frequency: 110.000,
    },
    {
      name: 'G♯2/A♭2',
      natural: false,
      note: 'A♭',
      octave: 2,
      frequency: 103.826,
    },
    {
      name: 'G2',
      natural: true,
      note: 'G',
      octave: 2,
      frequency: 97.9989,
    },
    {
      name: 'F♯2/G♭2',
      natural: false,
      note: 'G♭',
      octave: 2,
      frequency: 92.4986,
    },
    {
      name: 'F2',
      natural: true,
      note: 'F',
      octave: 2,
      frequency: 87.3071,
    },
    {
      name: 'E2',
      natural: true,
      note: 'E',
      octave: 2,
      frequency: 82.4069,
    },
    {
      name: 'D♯2/E♭2',
      natural: false,
      note: 'E♭',
      octave: 2,
      frequency: 77.7817,
    },
    {
      name: 'D2',
      natural: true,
      note: 'D',
      octave: 2,
      frequency: 73.4162,
    },
    {
      name: 'C♯2/D♭2',
      natural: false,
      note: 'D♭',
      octave: 2,
      frequency: 69.2957,
    },
    {
      name: 'C2',
      natural: true,
      note: 'C',
      octave: 2,
      frequency: 65.4064,
    },
    {
      name: 'B1',
      natural: true,
      note: 'B',
      octave: 1,
      frequency: 61.7354,
    },
    {
      name: 'A♯1/B♭1',
      natural: false,
      note: 'B♭',
      octave: 1,
      frequency: 58.2705,
    },
    {
      name: 'A1',
      natural: true,
      note: 'A',
      octave: 1,
      frequency: 55.0000,
    },
    {
      name: 'G♯1/A♭1',
      natural: false,
      note: 'A♭',
      octave: 1,
      frequency: 51.9131,
    },
    {
      name: 'G1',
      natural: true,
      note: 'G',
      octave: 1,
      frequency: 48.9994,
    },
    {
      name: 'F♯1/G♭1',
      natural: false,
      note: 'G♭',
      octave: 1,
      frequency: 46.2493,
    },
    {
      name: 'F1',
      natural: true,
      note: 'F',
      octave: 1,
      frequency: 43.6535,
    },
    {
      name: 'E1',
      natural: true,
      note: 'E',
      octave: 1,
      frequency: 41.2034,
    },
    {
      name: 'D♯1/E♭1',
      natural: false,
      note: 'E♭',
      octave: 1,
      frequency: 38.8909,
    },
    {
      name: 'D1',
      natural: true,
      note: 'D',
      octave: 1,
      frequency: 36.7081,
    },
    {
      name: 'C♯1/D♭1',
      natural: false,
      note: 'D♭',
      octave: 1,
      frequency: 34.6478,
    },
    {
      name: 'C1',
      natural: true,
      note: 'C',
      octave: 1,
      frequency: 32.7032,
    },
    {
      name: 'B0',
      natural: true,
      note: 'B',
      octave: 0,
      frequency: 30.8677,
    },
    {
      name: 'A♯0/B♭0',
      natural: false,
      note: 'B♭',
      octave: 0,
      frequency: 29.1352,
    },
    {
      name: 'A0',
      natural: true,
      note: 'A',
      octave: 0,
      frequency:  27.5000
    }
  ];

  function get(name) {
    var found = false;
    angular.forEach(all, function(note) {
      if (note.name === name) {
        found = note;
      }
    });
    return found;
  }

  function notes() {
    return {all, get};
  }

  angular.module('app').service('notes', notes);
})();
